name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  push:
    branches:
      - dev
jobs:
  example01:
    runs-on: ubuntu-latest
    steps:
      - run: echo push on dev
